version: '3'

services: 
  vote:
    image: voting-vote:latest
    container_name: vote
    ports:
      - "60001:80"
  redis:
    image: redis:alpine
    container_name: redis
  worker:
    image: voting-worker:latest
    container_name: worker
  db:
    image: postgres:9.4
    container_name: db
    environment: 
      POSTGRES_HOST_AUTH_METHOD: trust
  result:
    image: voting-result:latest
    container_name: result
    ports:
      - "60002:80"
