version: '3'

services:
  ghost:
    image: ghost:3.41.5-alpine
    ports:
      - "60000:2368"
    volumes:
      - ./ghost_data:/var/lib/ghost/content
    environment:
      url: http://localhost:60000